### ISSUE TITLE
Задачи раз

### ISSUE THREAD

**Issue by KishkaShocoladki** [KishkaShocoladki/doors#1]
- создать детальную форму двери(одну для всех)
- сделать так, чтобы по клику на картинку двери на main открывалась ее детальная форма
- добавить больше параметров дверей(comboBox'ы) на main(т.е. это цвет, ширина, тип древесины и проч.)
- опционально: можно вставить адекватные картинки дверей(не думаю, что сейчас от них какой-то толк)

**Comment by mabramovsd** [comment]
https://docs.google.com/document/d/1DVkudVb_S11II8YGHELQv1AV_7k4jgRH2opX1_-cGCY/edit
